// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnek-KtCW20H_8eKryofTtG1ldThEXYsE',
    appId: '1:968376714971:web:72767f12575f782590eefe',
    messagingSenderId: '968376714971',
    projectId: 'ctse-project-8cb36',
    authDomain: 'ctse-project-8cb36.firebaseapp.com',
    storageBucket: 'ctse-project-8cb36.appspot.com',
    measurementId: 'G-X7J40S4QE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUzdFx7IzwV1vsirgWPQi2kT0SpREmyKk',
    appId: '1:968376714971:android:96bf8a4f6e92b02290eefe',
    messagingSenderId: '968376714971',
    projectId: 'ctse-project-8cb36',
    storageBucket: 'ctse-project-8cb36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIMWoUQqYj_D9dfNBHzKNRdoLmjbkjQZA',
    appId: '1:968376714971:ios:5645126482b69ba290eefe',
    messagingSenderId: '968376714971',
    projectId: 'ctse-project-8cb36',
    storageBucket: 'ctse-project-8cb36.appspot.com',
    iosClientId: '968376714971-4f5dj1i7dbl2l011lnbo89j1u1jlt1u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIMWoUQqYj_D9dfNBHzKNRdoLmjbkjQZA',
    appId: '1:968376714971:ios:5645126482b69ba290eefe',
    messagingSenderId: '968376714971',
    projectId: 'ctse-project-8cb36',
    storageBucket: 'ctse-project-8cb36.appspot.com',
    iosClientId: '968376714971-4f5dj1i7dbl2l011lnbo89j1u1jlt1u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNew',
  );
}
